on:
    push:
    pull_request:
        types: [opened, synchronize, reopened]

env:
        MIRROR_URL: "git@github.com:EpitechPromo2028/B-MUL-200-LIL-2-1-myrpg-clement.bouret.git"
        PROJECT_NAME: "myrpg"
        PUSH_BRANCH: "${{ github.ref }}"
        PUSHER: "${{ github.actor }}"
        REPOSITORY: "${{ github.repository }}"

jobs:
    is_repo_a_mirror:
      runs-on: ubuntu-latest
      if : github.repository != 'EpitechPromo2028/B-MUL-200-LIL-2-1-myrpg-clement.bouret.git'
      steps:
        - name: Check if repo is a mirror
          run: |
            if [[ "${GITHUB_REPOSITORY}" == "${MIRROR_URL}" ]]; then
              echo "Error: This repository is a mirror"
              exit 1
            else
              echo "This repository is not a mirror"
              exit 0
            fi
    check_coding_style:
      runs-on: ubuntu-latest
      needs: is_repo_a_mirror
      container:
          image: "ghcr.io/epitech/coding-style-checker:latest"
          options: --privileged
      steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Coding Style
        run: |
          check.sh . /tmp
      - name: Annotation
        run: |
          input=/tmp/coding-style-reports.log
          while IFS= read -r -a line; do
            fields=($(printf "%s" "$line"|cut -d':' --output-delimiter=' ' -f1-))
            echo "::error title=${fields[2]} coding style error,file=${fields[0]},line=${fields[1]}::${fields[3]}"
          done < $input
      - name: Result
        run: |
          NB_ERROR=$(cat /tmp/coding-style-reports.log | wc -l)
          if [ $NB_ERROR -gt 0 ]; then
            exit 1
          fi
    build:
        runs-on: ubuntu-latest
        needs: is_repo_a_mirror
        container:
            image: epitechcontent/epitest-docker:latest
            options: --privileged
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build
              run: make
    deploy:
      runs-on: ubuntu-latest
      needs: [build, check_coding_style]
      if: github.repository != 'EpitechPromo2028/B-MUL-200-LIL-2-1-myrpg-clement.bouret.git'
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Push Epitech
          uses: pixta-dev/repository-mirroring-action@v1
          with:
            target_repo_url: ${{ env.MIRROR_URL }}
            ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
    discord_report:
      runs-on: ubuntu-latest
      needs: deploy
      steps:
        - name: Discord Webhook Action
          uses: tsickert/discord-webhook@v6.0.0
          with:
            webhook-url: ${{ secrets.WEBHOOK_URL }}
            embed-title: "REPORT LOG - ${{ env.PROJECT_NAME }}"
            embed-description: "A new report has been generated for **${{ env.PROJECT_NAME }}** project by Github Actions. The push has been made by **${{ env.PUSHER }}** on the branch **${{ env.PUSH_BRANCH }}** on the repository **${{ env.REPOSITORY }}**."
            embed-color: "3066993"
            embed-image-url: "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png"