name: Generate Doxygen Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.PRIVATE_TOKEN }}
          branch: gh-pages
          folder: html
          config_file: Doxyfile
