on:
    push:

env:
    MIRROR_URL: "git@github.com:EpitechPromo2028/B-MUL-200-LIL-2-1-mypaint-alexandre.garbe.git"
    EXECUTABLE_NAME: "my_paint"

jobs:
    check_repos_size:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: echo-size
          run: du -skh --exclude=".git" --exclude=".github" --exclude=".vscode"
    build:
        runs-on: ubuntu-latest
        container:
            image: epitechcontent/epitest-docker:latest
            options: --privileged
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build
              run: make
    check_coding_style:
      runs-on: ubuntu-latest
      container: ghcr.io/epitech/coding-style-checker:latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Check coding style
          run: |
            check.sh $(pwd) $(pwd)
            CODING_STYLE_ERRORS=$(cat $(pwd)/coding-style-reports.log)
            for ERRORS in $CODING_STYLE_ERRORS; do
              array=(`echo $ERRORS | sed 's/:/\n/g'`)
              echo "::error file=${array[1]#./},title=${array[3]#./} coding style errors detected: ${array[2]#./}::${array[4]#./}"
            done
            if [[ -n $CODING_STYLE_ERRORS ]]
            then
              exit 1
            else
              echo No coding style errors detected
            fi
    deploy:
        runs-on: ubuntu-latest
        needs: [build, check_coding_style, check_repos_size]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Push Epitech
              uses: pixta-dev/repository-mirroring-action@v1
              with:
                target_repo_url:
                  ${{ env.MIRROR_URL }}
                ssh_private_key:
                  ${{ secrets.SSH_PRIVATE_KEY }}
